version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webpsy
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootpass
    ports:
      - "3000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
